# Generated by Django 4.0.4 on 2022-04-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(default=1, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
